
package pl.edu.agh.soa.parking_system.soap;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebServiceClient(name = "PlaceSensorMockImplService", targetNamespace = "http://soap.parking_system.soa.agh.edu.pl/", wsdlLocation = "http://localhost:8080/soap/parkingsystem?wsdl")
public class PlaceSensorMockImplService
        extends Service {

    private final static URL PLACESENSORMOCKIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException PLACESENSORMOCKIMPLSERVICE_EXCEPTION;
    private final static QName PLACESENSORMOCKIMPLSERVICE_QNAME = new QName("http://soap.parking_system.soa.agh.edu.pl/", "PlaceSensorMockImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/soap/parkingsystem?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PLACESENSORMOCKIMPLSERVICE_WSDL_LOCATION = url;
        PLACESENSORMOCKIMPLSERVICE_EXCEPTION = e;
    }

    public PlaceSensorMockImplService() {
        super(__getWsdlLocation(), PLACESENSORMOCKIMPLSERVICE_QNAME);
    }

    public PlaceSensorMockImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PLACESENSORMOCKIMPLSERVICE_QNAME, features);
    }

    public PlaceSensorMockImplService(URL wsdlLocation) {
        super(wsdlLocation, PLACESENSORMOCKIMPLSERVICE_QNAME);
    }

    public PlaceSensorMockImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PLACESENSORMOCKIMPLSERVICE_QNAME, features);
    }

    public PlaceSensorMockImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PlaceSensorMockImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * @return returns PlaceSensorMock
     */
    @WebEndpoint(name = "PlaceSensorMockServicePort")
    public PlaceSensorMock getPlaceSensorMockServicePort() {
        return super.getPort(new QName("http://soap.parking_system.soa.agh.edu.pl/", "PlaceSensorMockServicePort"), PlaceSensorMock.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns PlaceSensorMock
     */
    @WebEndpoint(name = "PlaceSensorMockServicePort")
    public PlaceSensorMock getPlaceSensorMockServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.parking_system.soa.agh.edu.pl/", "PlaceSensorMockServicePort"), PlaceSensorMock.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PLACESENSORMOCKIMPLSERVICE_EXCEPTION != null) {
            throw PLACESENSORMOCKIMPLSERVICE_EXCEPTION;
        }
        return PLACESENSORMOCKIMPLSERVICE_WSDL_LOCATION;
    }

}
